config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only:[:index, :new, :create, :destroy]
  resources :users, only:[:index, :new, :create, :show,]
  resources :articles do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  with_options unless: :image? do
    validates :content, presence: true
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum:30 }
  validates :email, presence: true, length: { maximum:255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
    uniqueness: true
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum:8 }
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_id, only: [:edit,  :destroy, :update, :show]

  def index
    @users = User.all
    if current_user.present?
      @articles = Article.where(user_id: current_user.id).reverse
    else
      @articles = []
    end
    @article = Article.new
  end

  def new
    if params[:back]
      @article = Article.new(article_params)
    else
      @article = Article.new
    end
  end

  def confirm
    @article = Article.new(article_params)
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if params[:back]
      render :index
    else
      article_check(@article.update(article_params), "create")
    end
  end

  def show
    @users = User.all
  end

  def edit
  end

  def update
    @article = Article.find(params[:id])
    article_check(@article.update(article_params), "update")
  end

  def destroy
    @article.destroy
    redirect_to articles_path, notice:"記事を削除しました"
  end

  private
  def article_params
    params.require(:article).permit(:id, :content, :image, :image_cache, :remove_image)
  end

  def set_id
    @article = Article.find(params[:id])
  end

  def article_check(check, name)
    if check
      case name
      when "create" then
      redirect_to articles_path, notice: "記事を投稿しました"
      when "update" then
      redirect_to articles_path, notice: "記事を編集しました"
      end
    else
      redirect_to articles_path, notice: "投稿できませんでした"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    flash[:notice] = "ログインしました"
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to articles_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @article, url: articles_path, local: true) do |form| %>
  <%= image_tag(@article.image.url) if @article.image && @article.image.url %>
  <%= content_tag(:div, @article.content)  %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "投稿する" %>
<% end %>
<%= form_with(model:@article, url:articles_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/articles/edit.html.erb
<h1>編集画面</h1>
<div id="article_form" class="box single">
  <div class="column_title">投稿を作成</div>
  <a href="" class="prof_icon"></a>
  <%= form_with(model: @article, local: true) do |form| %>
    <%= form.text_area :content, placeholder:"#{current_user.name}さん - 今なにしてる？" %>
    <div id="img_field_edit" onClick="$('#file').click()" >
      <% if @article.image.url.present? %>
        <%= image_tag(@article.image.url) %>
      <% end %>
    </div>
    <div class="field">
      <%= form.file_field :image, style: "display:none;", id: "file"%>
    </div>
    <%= form.submit "投稿する", class:"btn_submit" %>
    <%= form.submit "戻る", name: "back" %>
  <% end %>
</div>
<script>
$(function() {
  $fileField = $('#file')
  $($fileField).on('change', $fileField, function(e) {
    file = e.target.files[0]
    reader = new FileReader(),
    $preview = $("#img_field");
    reader.onload = (function(file) {
      return function(e) {
        $preview.empty();
        $preview.append($('<img>').attr({
          src: e.target.result,
          width: "100%",
          class: "preview",
          title: file.name
        }));
      };
    })(file);
    reader.readAsDataURL(file);
  });
  autosize($('textarea'));
});
</script>

app/views/articles/index.html.erb
<div id="left_navi">
  <nav>
    <ul>
      <li>left navi 1</li>
      <li>left navi 2</li>
      <li>left navi 3</li>
    </ul>
  </nav>
</div>
<div></div>
<div id="center_content">
  <% flash.each do |key,value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <% if current_user.present? %>
  <div id="article_form" class="box">
    <div class="column_title">投稿を作成</div>
    <a href="" class="prof_icon"></a>
    <%= form_with(model: @article, local: true, url:confirm_articles_path) do |form| %>
      <%= form.text_area :content, placeholder:"#{current_user.name}さん - 今なにしてる？" %>
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this feed from being saved:</h2>
          <ul>
          <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :image %>
        <%= image_tag(@article.image.url) if @article.image && @article.image.url %>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>
      </div>
      <%= form.submit "投稿する", class:"btn_submit" %>
    <% end %>
  </div>
  <% end %>
  <div id="logs">
    <ul>
    <% @articles.each do |log| %>
      <li class="box">
        <div class="head">
          <div class="article_name"><%= @users.find_by(id: log.user_id).name %></div>
        </div>
        <div class="content">
          <div class="comment"><%= simple_format(log.content) %></div>
          <% if log.image? %>
          <div class="thumbnail">
            <%= image_tag log.image.url %>
          </div>
          <% end %>
        </div>
        <div class="article_menu">
          <ul>
            <li><%= link_to "詳細", article_path(log.id) %></li>
            <li><%= link_to "編集", edit_article_path(log.id) %></li>
            <li><%= link_to "削除", article_path(log.id), method: :delete %></li>
          </ul>
        </div>
      </li>
    <% end %>
    </ul>
  </div>
</div>
<div id="right_content">
  <ul id="r_bax1" class="box">
    <li>right navi 1</li>
    <li>right navi 2</li>
    <li>right navi 3</li>
  </ul>
  <div class="box">右カラム</div>
</div>

app/views/articles/show.html.erb
<h1>自分の投稿</h1>
<div id="profile">
  <div id="prof_left">
    <a href="<%= edit_user_path %>">
      <%= image_tag(current_user.image.url), class: 'resize' if current_user.image && current_user.image.url %>
    </a>
  </div>
  <ul id="prof_right">
    <li><%= current_user.name %></li>
    <li><%= current_user.comment %></li>
  </ul>
</div>

<div id="articles">
  <ul>
    <% @articles.each do |log| %>
    <li>
      <a href="<%= log.id %>">
      </a>
    </li>
    <% end %>
  </ul>
</div>
<script>
  $(function() {
    $(".resize").ajustImg();

    function ajustImg(){
      let img = $(this);
      let box = img.parent();

      let ajust = ajust_direction(box,img);
      if (ajust == "x"){
        img.css({'width':'100%'});
      }else{
        img.css({'height':'100%'});
      }

      function ajust_direction(b,i){
        function aspect_ratio(object){
          return object.width() / object.height();
        }
        let box_aspect = aspect_ratio(b);
        let img_aspect = aspect_ratio(i);
        let direction;
        switch(true){
          case box_aspect == 1:
            if (img_aspect > 1){
              direction = "y";
            }
            else{
              direction = "x";
            }
            break;
          case box_aspect > 1:
            if (box_aspect > i){
              direction = "x";
            }else {
              direction = "y";
            };
            break;
          case box_aspect < 1:
            if (box_aspect > img_aspect){
              direction = "y";
            }else {
              direction = "x";
            };
            break;
        }
        return direction;
      }
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
  		$(function() {
  			autosize($('textarea'));
  		});
  	</script>
  </head>
  <body>
    <header>
      <nav class="navbar">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="<%= articles_path %>">Fakebook</a>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <% if current_user.present? %>
              <li><a href="<%= user_path(current_user.id) %>"><%= current_user.name %></a></li>
              <% end %>
              <li><a href="">menu1</a></li>
              <li><a href="">menu2</a></li>
              <% if logged_in? %>
                <li><%= link_to "Profile", user_path(current_user.id) %></li>
                <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_path %></li>
                <li><%= link_to "Login", new_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div id="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Fakebook</h1>
<%= link_to "Log in", new_session_path %>
<%= link_to "Sign up", new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>prohibited this @user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "sign up" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<%= link_to "記事一覧", articles_path %>